package com.juniperGMVAD.app;

/*
 * T[] values()           -- implicit method for all enum types, returns list of each constant
 * T valueOf(String name) -- implicit method, returns constant with given name
 * https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html#valueOf-java.lang.Class-java.lang.String-
 */

public enum Country {
    ABW("Aruba","ABW"),
    AFE("Africa Eastern and Southern","AFE"),
    AFG("Afghanistan","AFG"),
    AFW("Africa Western and Central","AFW"),
    AGO("Angola","AGO"),
    ALB("Albania","ALB"),
    AND("Andorra","AND"),
    ARB("Arab World","ARB"),
    ARE("United Arab Emirates","ARE"),
    ARG("Argentina","ARG"),
    ARM("Armenia","ARM"),
    ASM("American Samoa","ASM"),
    ATG("Antigua and Barbuda","ATG"),
    AUS("Australia","AUS"),
    AUT("Austria","AUT"),
    AZE("Azerbaijan","AZE"),
    BDI("Burundi","BDI"),
    BEL("Belgium","BEL"),
    BEN("Benin","BEN"),
    BFA("Burkina Faso","BFA"),
    BGD("Bangladesh","BGD"),
    BGR("Bulgaria","BGR"),
    BHR("Bahrain","BHR"),
    BHS("Bahamas, The","BHS"),
    BIH("Bosnia and Herzegovina","BIH"),
    BLR("Belarus","BLR"),
    BLZ("Belize","BLZ"),
    BMU("Bermuda","BMU"),
    BOL("Bolivia","BOL"),
    BRA("Brazil","BRA"),
    BRB("Barbados","BRB"),
    BRN("Brunei Darussalam","BRN"),
    BTN("Bhutan","BTN"),
    BWA("Botswana","BWA"),
    CAF("Central African Republic","CAF"),
    CAN("Canada","CAN"),
    CEB("Central Europe and the Baltics","CEB"),
    CHE("Switzerland","CHE"),
    CHI("Channel Islands","CHI"),
    CHL("Chile","CHL"),
    CHN("China","CHN"),
    CIV("Cote d'Ivoire","CIV"),
    CMR("Cameroon","CMR"),
    COD("Congo, Dem. Rep.","COD"),
    COG("Congo, Rep.","COG"),
    COL("Colombia","COL"),
    COM("Comoros","COM"),
    CPV("Cabo Verde","CPV"),
    CRI("Costa Rica","CRI"),
    CSS("Caribbean small states","CSS"),
    CUB("Cuba","CUB"),
    CUW("Curacao","CUW"),
    CYM("Cayman Islands","CYM"),
    CYP("Cyprus","CYP"),
    CZE("Czechia","CZE"),
    DEU("Germany","DEU"),
    DJI("Djibouti","DJI"),
    DMA("Dominica","DMA"),
    DNK("Denmark","DNK"),
    DOM("Dominican Republic","DOM"),
    DZA("Algeria","DZA"),
    EAP("East Asia & Pacific (excluding high income)","EAP"),
    EAR("Early-demographic dividend","EAR"),
    EAS("East Asia & Pacific","EAS"),
    ECA("Europe & Central Asia (excluding high income)","ECA"),
    ECS("Europe & Central Asia","ECS"),
    ECU("Ecuador","ECU"),
    EGY("Egypt, Arab Rep.","EGY"),
    EMU("Euro area","EMU"),
    ERI("Eritrea","ERI"),
    ESP("Spain","ESP"),
    EST("Estonia","EST"),
    ETH("Ethiopia","ETH"),
    EUU("European Union","EUU"),
    FCS("Fragile and conflict affected situations","FCS"),
    FIN("Finland","FIN"),
    FJI("Fiji","FJI"),
    FRA("France","FRA"),
    FRO("Faroe Islands","FRO"),
    FSM("Micronesia, Fed. Sts.","FSM"),
    GAB("Gabon","GAB"),
    GBR("United Kingdom","GBR"),
    GEO("Georgia","GEO"),
    GHA("Ghana","GHA"),
    GIB("Gibraltar","GIB"),
    GIN("Guinea","GIN"),
    GMB("Gambia, The","GMB"),
    GNB("Guinea-Bissau","GNB"),
    GNQ("Equatorial Guinea","GNQ"),
    GRC("Greece","GRC"),
    GRD("Grenada","GRD"),
    GRL("Greenland","GRL"),
    GTM("Guatemala","GTM"),
    GUM("Guam","GUM"),
    GUY("Guyana","GUY"),
    HIC("High income","HIC"),
    HKG("Hong Kong SAR, China","HKG"),
    HND("Honduras","HND"),
    HPC("Heavily indebted poor countries (HIPC)","HPC"),
    HRV("Croatia","HRV"),
    HTI("Haiti","HTI"),
    HUN("Hungary","HUN"),
    IBD("IBRD only","IBD"),
    IBT("IDA & IBRD total","IBT"),
    IDA("IDA total","IDA"),
    IDB("IDA blend","IDB"),
    IDN("Indonesia","IDN"),
    IDX("IDA only","IDX"),
    IMN("Isle of Man","IMN"),
    IND("India","IND"),
    INX("Not classified","INX"),
    IRL("Ireland","IRL"),
    IRN("Iran, Islamic Rep.","IRN"),
    IRQ("Iraq","IRQ"),
    ISL("Iceland","ISL"),
    ISR("Israel","ISR"),
    ITA("Italy","ITA"),
    JAM("Jamaica","JAM"),
    JOR("Jordan","JOR"),
    JPN("Japan","JPN"),
    KAZ("Kazakhstan","KAZ"),
    KEN("Kenya","KEN"),
    KGZ("Kyrgyz Republic","KGZ"),
    KHM("Cambodia","KHM"),
    KIR("Kiribati","KIR"),
    KNA("St. Kitts and Nevis","KNA"),
    KOR("Korea, Rep.","KOR"),
    KWT("Kuwait","KWT"),
    LAC("Latin America & Caribbean (excluding high income)","LAC"),
    LAO("Lao PDR","LAO"),
    LBN("Lebanon","LBN"),
    LBR("Liberia","LBR"),
    LBY("Libya","LBY"),
    LCA("St. Lucia","LCA"),
    LCN("Latin America & Caribbean","LCN"),
    LDC("Least developed countries: UN classification","LDC"),
    LIC("Low income","LIC"),
    LIE("Liechtenstein","LIE"),
    LKA("Sri Lanka","LKA"),
    LMC("Lower middle income","LMC"),
    LMY("Low & middle income","LMY"),
    LSO("Lesotho","LSO"),
    LTE("Late-demographic dividend","LTE"),
    LTU("Lithuania","LTU"),
    LUX("Luxembourg","LUX"),
    LVA("Latvia","LVA"),
    MAC("Macao SAR, China","MAC"),
    MAF("St. Martin (French part)","MAF"),
    MAR("Morocco","MAR"),
    MCO("Monaco","MCO"),
    MDA("Moldova","MDA"),
    MDG("Madagascar","MDG"),
    MDV("Maldives","MDV"),
    MEA("Middle East & North Africa","MEA"),
    MEX("Mexico","MEX"),
    MHL("Marshall Islands","MHL"),
    MIC("Middle income","MIC"),
    MKD("North Macedonia","MKD"),
    MLI("Mali","MLI"),
    MLT("Malta","MLT"),
    MMR("Myanmar","MMR"),
    MNA("Middle East & North Africa (excluding high income)","MNA"),
    MNE("Montenegro","MNE"),
    MNG("Mongolia","MNG"),
    MNP("Northern Mariana Islands","MNP"),
    MOZ("Mozambique","MOZ"),
    MRT("Mauritania","MRT"),
    MUS("Mauritius","MUS"),
    MWI("Malawi","MWI"),
    MYS("Malaysia","MYS"),
    NAC("North America","NAC"),
    NAM("Namibia","NAM"),
    NCL("New Caledonia","NCL"),
    NER("Niger","NER"),
    NGA("Nigeria","NGA"),
    NIC("Nicaragua","NIC"),
    NLD("Netherlands","NLD"),
    NOR("Norway","NOR"),
    NPL("Nepal","NPL"),
    NRU("Nauru","NRU"),
    NZL("New Zealand","NZL"),
    OED("OECD members","OED"),
    OMN("Oman","OMN"),
    OSS("Other small states","OSS"),
    PAK("Pakistan","PAK"),
    PAN("Panama","PAN"),
    PER("Peru","PER"),
    PHL("Philippines","PHL"),
    PLW("Palau","PLW"),
    PNG("Papua New Guinea","PNG"),
    POL("Poland","POL"),
    PRE("Pre-demographic dividend","PRE"),
    PRI("Puerto Rico","PRI"),
    PRK("Korea, Dem. People's Rep.","PRK"),
    PRT("Portugal","PRT"),
    PRY("Paraguay","PRY"),
    PSE("West Bank and Gaza","PSE"),
    PSS("Pacific island small states","PSS"),
    PST("Post-demographic dividend","PST"),
    PYF("French Polynesia","PYF"),
    QAT("Qatar","QAT"),
    ROU("Romania","ROU"),
    RUS("Russian Federation","RUS"),
    RWA("Rwanda","RWA"),
    SAS("South Asia","SAS"),
    SAU("Saudi Arabia","SAU"),
    SDN("Sudan","SDN"),
    SEN("Senegal","SEN"),
    SGP("Singapore","SGP"),
    SLB("Solomon Islands","SLB"),
    SLE("Sierra Leone","SLE"),
    SLV("El Salvador","SLV"),
    SMR("San Marino","SMR"),
    SOM("Somalia","SOM"),
    SRB("Serbia","SRB"),
    SSA("Sub-Saharan Africa (excluding high income)","SSA"),
    SSD("South Sudan","SSD"),
    SSF("Sub-Saharan Africa","SSF"),
    SST("Small states","SST"),
    STP("Sao Tome and Principe","STP"),
    SUR("Suriname","SUR"),
    SVK("Slovak Republic","SVK"),
    SVN("Slovenia","SVN"),
    SWE("Sweden","SWE"),
    SWZ("Eswatini","SWZ"),
    SXM("Sint Maarten (Dutch part)","SXM"),
    SYC("Seychelles","SYC"),
    SYR("Syrian Arab Republic","SYR"),
    TCA("Turks and Caicos Islands","TCA"),
    TCD("Chad","TCD"),
    TEA("East Asia & Pacific (IDA & IBRD countries)","TEA"),
    TEC("Europe & Central Asia (IDA & IBRD countries)","TEC"),
    TGO("Togo","TGO"),
    THA("Thailand","THA"),
    TJK("Tajikistan","TJK"),
    TKM("Turkmenistan","TKM"),
    TLA("Latin America & the Caribbean (IDA & IBRD countries)","TLA"),
    TLS("Timor-Leste","TLS"),
    TMN("Middle East & North Africa (IDA & IBRD countries)","TMN"),
    TON("Tonga","TON"),
    TSA("South Asia (IDA & IBRD)","TSA"),
    TSS("Sub-Saharan Africa (IDA & IBRD countries)","TSS"),
    TTO("Trinidad and Tobago","TTO"),
    TUN("Tunisia","TUN"),
    TUR("Turkiye","TUR"),
    TUV("Tuvalu","TUV"),
    TZA("Tanzania","TZA"),
    UGA("Uganda","UGA"),
    UKR("Ukraine","UKR"),
    UMC("Upper middle income","UMC"),
    URY("Uruguay","URY"),
    USA("United States","USA"),
    UZB("Uzbekistan","UZB"),
    VCT("St. Vincent and the Grenadines","VCT"),
    VEN("Venezuela, RB","VEN"),
    VGB("British Virgin Islands","VGB"),
    VIR("Virgin Islands (U.S.)","VIR"),
    VNM("Viet Nam","VNM"),
    VUT("Vanuatu","VUT"),
    WLD("World","WLD"),
    WSM("Samoa","WSM"),
    XKX("Kosovo","XKX"),
    YEM("Yemen, Rep.","YEM"),
    ZAF("South Africa","ZAF"),
    ZMB("Zambia","ZMB"),
    ZWE("Zimbabwe","ZWE");

    private final String name;
    private final String code;

    Country(String name, String code) {
        this.name = name;
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public String getCode() {
        return code;
    }
}
