
all: p1 p2 p3 p4 q1 q2

clean:
	rm -f p1 p2 p3 p4 q1 q2

p1: p1.c
	gcc -o p1 p1.c -Wall

p2: p2.c
	gcc -o p2 p2.c -Wall

p3: p3.c
	gcc -o p3 p3.c -Wall

p4: p4.c
	gcc -o p4 p4.c -Wall

q1: q1.c
	gcc -o q1 q1.c -Wall

q2: q2.c
	qcc -o q2 q2.c -Wall